steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/orders-microservice -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/orders-microservice',
      ]

availableSecrets:
  secretManager:
  - versionName: projects/980237481565/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
